version: "2"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: AvGhTeQcGHyooPL
            MYSQL_DATABASE: animeshop
            MYSQL_USER: animeshop
            MYSQL_PASSWORD: AvGhTeQcGHyooPL
    app:
        image: ram2701/animeshop:latest
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8443"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/animeshop?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: animeshop
            SPRING_DATASOURCE_PASSWORD: AvGhTeQcGHyooPL